version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    volumes:
      - "postgres-db:/var/lib/postgresql/data"
      - "./docker/postgres.conf:/etc/postgresql/postgres.conf"
    ports:
      - "5432:5432"

volumes:
  postgres-db:
